version: "3.8"
name: python-flask

services:
  web:
    build: .
    command: python3 -m gunicorn app:app
    ports:
      - "8000:${PORT}"
    env_file:
      - .env
    environment:
      GUNICORN_CMD_ARGS: --bind=0.0.0.0:${PORT} --workers=${GUNICORN_WORKERS}
    volumes:
      - type: bind
        source: ./flask_app/instance/survey.db
        target: /app/flask_app/instance/survey.db